"""empty message

Revision ID: 399fbcb9d88b
Revises: c5d2c44b1d13
Create Date: 2022-08-18 18:00:53.362484

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '399fbcb9d88b'
down_revision = 'c5d2c44b1d13'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('venue', sa.Column('seeking_talent', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('venue', 'seeking_talent')
    # ### end Alembic commands ###
